---
resources:
  - service_account.yaml
  - role.yaml
  - role_binding.yaml
  - metrics_auth_role.yaml
  - metrics_auth_role_binding.yaml
  - metrics_reader_role.yaml
  - runner_admin_role.yaml
  - runner_editor_role.yaml
  - runner_viewer_role.yaml
  - renovateconfig_admin_role.yaml
  - renovateconfig_editor_role.yaml
  - renovateconfig_viewer_role.yaml
  - gitrepo_admin_role.yaml
  - gitrepo_editor_role.yaml
  - gitrepo_viewer_role.yaml
  - renovator_admin_role.yaml
  - renovator_editor_role.yaml
  - renovator_viewer_role.yaml
