---
apiVersion: renovate.thegeeklab.de/v1beta1
kind: RenovateConfig
metadata:
  labels:
    app.kubernetes.io/name: renovate-operator
    app.kubernetes.io/managed-by: kustomize
  name: renovateconfig-sample
spec:
# TODO(user): Add fields here
