---
apiVersion: renovate.thegeeklab.de/v1beta1
kind: Discovery
metadata:
  labels:
    app.kubernetes.io/name: renovate-operator
    app.kubernetes.io/managed-by: kustomize
  name: discovery-sample
spec:
  image: "ghcr.io/thegeeklab/renovate-operator:latest"
  imagePullPolicy: "IfNotPresent"

  logging:
    level: "info"

  configRef: "renovate-config"

  suspend: false
  schedule: "0 */2 * * *"

  filter:
    - "my-org/*"
    - "another-org/important-repo"
