apiVersion: renovate.thegeeklab.de/v1beta1
kind: Scheduler
metadata:
  labels:
    app.kubernetes.io/name: renovate-operator
    app.kubernetes.io/managed-by: kustomize
  name: scheduler-sample
spec:
  # TODO(user): Add fields here
