---
apiVersion: renovate.thegeeklab.de/v1beta1
kind: Runner
metadata:
  labels:
    app.kubernetes.io/name: renovate-operator
    app.kubernetes.io/managed-by: kustomize
  name: runner-sample
spec:
  image: "ghcr.io/thegeeklab/renovate-operator:latest"
  imagePullPolicy: "IfNotPresent"

  logging:
    level: "info"

  configRef: "renovate-config"

  suspend: false
  schedule: "0 0 * * *"

  strategy: "batch"
  instances: 2
  batchSize: 10
