---
apiVersion: renovate.thegeeklab.de/v1beta1
kind: RenovateConfig
metadata:
  labels:
    app.kubernetes.io/name: renovate-operator
    app.kubernetes.io/managed-by: kustomize
  name: renovateconfig-sample
spec:
  image: "ghcr.io/renovatebot/renovate:latest"
  imagePullPolicy: "IfNotPresent"

  logging:
    level: "info"

  platform:
    type: "github"
    endpoint: "https://api.github.com"
    token:
      secretKeyRef:
        name: "github-token"
        key: "token"

  dryRun: "full"
  onboarding: true
  prHourlyLimit: 10
  addLabels:
    - "renovate"
    - "dependencies"
